---
 - hosts: localhost
   tasks:
     - name: ecr login
       shell: $(aws ecr get-login --no-include-email | sed 's|https://||')
     - name: Build python image
       docker_image:
         name: <aws ecr repo>
         tag: 1.0
         path: .
         state: present
     - name: pushing docker images
       shell: docker push <aws ecr repo>
     - name:  create contaner
       docker_container:
         name: container1
         state: present
         image: <aws ecr repo>:tag
         ports:
           - "8080:8080"
